modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/TheRealFloatDev/CreateBetterBuilding/issues"
license="GNU Lesser General Public License version 3 (LGPLv3)"

[[mods]]
modId = "create_better_building"
version = "${version}"
displayName = "Create: Better Building"
displayURL = "https://modrinth.com/mod/create-better-building/"
authors = "FloatDev"
description = '''
This mod adds a variety of new (mainly decorative) building blocks to the game, which are themed around Create and factories.
'''
logoFile = "logo.png"

[[dependencies.create_better_building]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_better_building]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_better_building]]
modId = "architectury"
mandatory = true
versionRange = "[6.6.92,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.create_better_building]]
modId="create"
mandatory=true
versionRange="[0,)"
ordering="NONE"
side="BOTH"
